trigger:
- main

pool:
  uipath

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Define the test case folder names
      $testCaseFolders = @("BPA_Column_Operation_01", "BPA_Column_Operation_02", "BPA_Column_Operation_03", "BPA_Column_Operation_06")
      
      # Loop through each test case folder
      foreach ($testCaseFolder in $testCaseFolders) {
        Write-Host "Processing test case: $testCaseFolder"
        
        # Build and publish the test case
        Write-Host "Building and publishing test case: $testCaseFolder"
        UiPathPack@4
          inputs:
            versionType: 'AutoVersion'
            projectJsonPath: "$(System.DefaultWorkingDirectory)/$testCaseFolder/project.json"
            orchestratorConnection: 'Uipath'
            outputPath: '$(Build.ArtifactStagingDirectory)/Output/$testCaseFolder'
        
        UiPathDeploy@4
          inputs:
            orchestratorConnection: 'Uipath'
            packagesPath: '$(Build.ArtifactStagingDirectory)/Output/$testCaseFolder'
            folderName: $testCaseFolder
      }
