trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  displayName: 'Pack and Deploy UiPath Projects'
  inputs:
    targetType: 'inline'
    script: |
      $projectFolders = Get-ChildItem -Path "$(System.DefaultWorkingDirectory)" -Directory -Name

      foreach ($folder in $projectFolders) {
        Write-Host "Processing folder: $folder"
        
        # Pack the project
        $outputPath = "$(Build.ArtifactStagingDirectory)\Output\$folder"
        New-Item -Path $outputPath -ItemType Directory -Force
        UiPath.Cmd pack "$(System.DefaultWorkingDirectory)\$folder\project.json" --output $outputPath
        
        # Deploy the package
        UiPath.Cmd deploy $outputPath --folder 'VariantMatrix' --orchestrator 'Uipath'
      }

