
trigger:
- main
 
pool:
  uipath
 
steps:
 
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/BPA_Column_Operation_01/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Create Required output folder'
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/BPA_Column_Operation_02/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Create Required output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/BPA_Column_Operation_03/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Create Required output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/BPA_Column_Operation_06/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- task: UiPathTest@4
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Uipath'
    testSet: 'VariantMatrix'
    folderName: 'Variant_Matrix_Automations'


