trigger:
- main

pool:
  uipath

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Fetch the latest code from the Git repository
- checkout: self

# Loop through each directory containing test cases
- bash: |
    shopt -s globstar
    for project in **/project.json; do
      dir=$(dirname "$project")
      echo "Building $dir..."
      uipath pack --projectJsonPath "$project" --outputPath "$(Build.ArtifactStagingDirectory)/$dir"
    done
  displayName: 'Build and pack test cases'

# Deploy the test cases to UiPath Orchestrator
- bash: |
    for package in $(find $(Build.ArtifactStagingDirectory) -name "*.nupkg"); do
      echo "Deploying $package..."
      uipath deploy --packagesPath $package --orchestratorConnection 'Uipath' --folderName 'VariantMatrix' # Update folderName as needed
    done
  displayName: 'Deploy test cases to UiPath Orchestrator'
