trigger:
- main

pool:
  uipath

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'BPA_Column_Operation_01/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'