trigger:
- main

pool:
  uipath

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Fetch the latest code from the Git repository
- checkout: self

# Loop through each directory containing test cases
- powershell: |
    foreach ($project in Get-ChildItem -Recurse -Filter "project.json") {
      $dir = $project.DirectoryName
      Write-Host "Building $dir..."
      uipath pack --projectJsonPath "$project.FullName" --outputPath "$(Build.ArtifactStagingDirectory)/$dir"
    }
  displayName: 'Build and pack test cases'

# Deploy the test cases to UiPath Orchestrator
- powershell: |
    foreach ($package in Get-ChildItem -Recurse -Filter "*.nupkg" -Path "$(Build.ArtifactStagingDirectory)") {
      Write-Host "Deploying $($package.FullName)..."
      uipath deploy --packagesPath $package.FullName --orchestratorConnection 'Uipath' --folderName 'VariantMatrix' # Update folderName as needed
    }
  displayName: 'Deploy test cases to UiPath Orchestrator'
