trigger:
- main

pool:
  uipath

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Fetch the latest code from the Git repository
- checkout: self

# Loop through each directory containing test cases
- powershell: |
    $projectFolders = Get-ChildItem -Directory -Path $(System.DefaultWorkingDirectory)
    foreach ($folder in $projectFolders) {
      $projectJson = Join-Path -Path $folder.FullName -ChildPath "project.json"
      if (Test-Path $projectJson) {
        Write-Host "Building $($folder.Name)..."
        dotnet build $projectJson --configuration Release
        dotnet pack $projectJson --output $(Build.ArtifactStagingDirectory)\$($folder.Name) --configuration Release
      } else {
        Write-Host "No project.json found in $($folder.Name). Skipping build."
      }
    }
  displayName: 'Build and pack test cases'

# Deploy the test cases to UiPath Orchestrator
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)'
    folderName: 'VariantMatrix' # Update this with the folder name where you want to deploy the packages

